name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: delete old container make sure to make it error free
        run: sudo docker rm -f rops-cont ||  true
      - name: pull from docker hub reg
        run: sudo docker pull gitkeeper05/rops:latest
      - name: Run
        run: sudo docker run -d -p 8080:80 --name rops-cont gitkeeper05/rops:latest
